name: Build and Test Sample

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string
      module:
        default: "app"
        type: string
    secrets:
      compose_store_password:
        description: 'password for the keystore'
        required: true
      compose_key_alias:
        description: 'alias for the keystore'
        required: true
      compose_key_password:
        description: 'password for the key'
        required: true
concurrency:
  group: ${{ inputs.name }}-build-${{ github.ref }}
  cancel-in-progress: true
env:
  compose_store_password: ${{ secrets.compose_store_password }}
  compose_key_alias: ${{ secrets.compose_key_alias }}
  compose_key_password: ${{ secrets.compose_key_password }}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # https://github.com/diffplug/spotless/issues/710
          # Check out full history for Spotless to ensure ratchetFrom can find the ratchet version
          fetch-depth: 0

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Generate cache key
        run: ./scripts/checksum.sh ${{ inputs.path }} checksum.txt

      - uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Check formatting
        working-directory: ${{ inputs.path }}
        run: ./gradlew spotlessCheck --stacktrace

      - name: Check lint
        working-directory: ${{ inputs.path }}
        run: ./gradlew lintDebug --stacktrace

      - name: Build debug
        working-directory: ${{ inputs.path }}
        run: ./gradlew assembleDebug --stacktrace
      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
      - name: Run local tests
        working-directory: ${{ inputs.path }}
        run: ./gradlew testDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v6
        with:
          name: build-outputs
          path: ${{ inputs.path }}/${{ inputs.module }}/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: build-reports
          path: ${{ inputs.path }}/${{ inputs.module }}/build/reports
