name: Jetcaster

on:
  push:
    paths:
      - 'Jetcaster/**'
  pull_request:
    paths:
      - 'Jetcaster/**'

env:
  SAMPLE_PATH: Jetcaster

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/jars-3
            ~/.gradle/caches/build-cache-1
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew spotlessCheck assembleDebug lintDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/app/build/reports
