name: Jetchat

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Jetchat.yaml'
      - 'Jetchat/**'
  pull_request:
    paths:
      - '.github/workflows/Jetchat.yaml'
      - 'Jetchat/**'
  workflow_dispatch:

env:
  SAMPLE_PATH: Jetchat
  compose_store_password: ${{ secrets.compose_store_password }}
  compose_key_alias: ${{ secrets.compose_key_alias }}
  compose_key_password: ${{ secrets.compose_key_password }}
jobs:
  build:
    uses: ./.github/workflows/build-sample.yml
    with:
      name: Jetchat
      path: Jetchat
    secrets:
      compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
      compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
      compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}
  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [23, 26, 29]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
          working-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-reports-jetchat-${{ matrix.api-level }}
          path: ${{ env.SAMPLE_PATH }}/app/build/reports
