name: GitHub Release with APKs

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v2    

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build all projects
        run: ./scripts/gradlew_recursive.sh assembleDebug

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Crane
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Crane/app/build/outputs/apk/debug/app-debug.apk
          asset_name: crane-debug.apk
          asset_content_type: application/vnd.android.package-archive          

      - name: Upload Owl
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Owl/app/build/outputs/apk/debug/app-debug.apk
          asset_name: owl-debug.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Jetcaster
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Jetcaster/app/build/outputs/apk/debug/app-debug.apk
          asset_name: jetcaster-debug.apk
          asset_content_type: application/vnd.android.package-archive          

      - name: Upload Jetchat
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Jetchat/app/build/outputs/apk/debug/app-debug.apk
          asset_name: jetchat-debug.apk
          asset_content_type: application/vnd.android.package-archive          

      - name: Upload Jetnews
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: JetNews/app/build/outputs/apk/debug/app-debug.apk
          asset_name: jetnews-debug.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Jetsnack
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Jetsnack/app/build/outputs/apk/debug/app-debug.apk
          asset_name: jetsnack-debug.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Jetsurvey
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Jetsurvey/app/build/outputs/apk/debug/app-debug.apk
          asset_name: jetsurvey-debug.apk
          asset_content_type: application/vnd.android.package-archive
