name: Build and Test a Compose snapshot

on:
  workflow_dispatch:
    inputs:
      snapshotID:
        required: true
        type: string
      composeVersion:
        required: true
        type: string

concurrency:
  group: ${{ inputs.name }}-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check snapshot
        working-directory: ${{ inputs.path }}
        run: ./scripts/test_snapshot.sh $CI_COMPOSE_VERSION $CI_COMPOSE_SNAPSHOT
        env:
          CI_COMPOSE_VERSION: ${{ inputs.composeVersion }}
          CI_COMPOSE_SNAPSHOT: ${{ inputs.snapshotID }}

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: ${{ inputs.path }}/app/build/reports
